# Basic settings
general:
  site_title: Jekyll Bigfoot
  description_text: Boilerplate using Jekyll and Sass, optimised for CloudCannon CMS
  site_url: 'https://mysite.com'
  site_logo_image: '/bigfoot.png'
  site_thumb_image: 'assets/images/placeholder-001.jpg'
  contact_email: 'example@me.com'
  phone_number: "+555 555 5555"
  address: 1 Main Street, Springfield 90009
  social:
    - id: "Facebook"
      url: https://facebook.com
    - id: "Instagram"
      url: https://instagram.com
    - id: "Twitter"
      url: https://twitter.com
    - id: "YouTube"
      url: https://youtube.com
    - id: "WhatsApp"
      url: https://whatsapp.com
navigation:
  menu_1_url: /about
  menu_2_url: /portfolio
  menu_3_url: /blog
  menu_4_url: /contact
  menu_5_url:
  menu_6_url:
# Brand identity
logos:
  navbar_logo_image: '/assets/logos/your-logo.png'
  footer_logo_image: '/assets/logos/your-logo-alternative.png'

# Adjustment of theme settings
theme:
  dark_color: "#222"
  light_color: "#555"
  accent_color: "#363e36"
  complementary_color: "#565"
  body_font_family: "'Nunito', sans-serif;"
  heading_font_family: "'Abril Fatface', cursive;"

# Typography (can be customized to accomodate more styles like standard font sizes and line height)
seo:
  keywords: [keyword, seo, optimization]
  description_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Analytics & embeds
configuration:
  head_code_block:  '<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Nunito&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">' # Place between single quotes
  footer_code_block:
  fb_app_id: 123456789
